version: '3.8'

services:
  # 1) Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    # 외부에 굳이 직접 노출하지 않을 거라면 ports 대신 expose 사용
    expose:
      - "8080"
    networks:
      - app-network

  # 2) Frontend + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    # 이 컨테이너가 Nginx 80 포트를 외부에 노출 → 최종 진입점
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
